app:
  grpc-gateway-port: 8090
  host: localhost
  port: 4000
  env: local
services:
  auth:
    scheme: http
    host: localhost
    url: "localhost:8080"
    port: 8080
  user:
    scheme: http
    host: localhost
    url: "localhost:9000"
    port: 9000
  graphql:
    scheme: http
    host: localhost:8000
    path: /query
